project_id = "yxjhungswhwahnbhahaq"

[functions.extract-template-styles]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.verify-admin-password]
verify_jwt = false

[functions.generate-test-images]
verify_jwt = false
